In [8]:
####Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
##to print the data types of both the variables.

##Importing numpy
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]

print(f"The list_ data type is: {type(list_)}")

array_list = np.array(object = list_)

print(f"The array_list data type is: {type(array_list)}")


print("list is a built-in data type which is also a mutable sequence of objects while Array is not a built-in data type in Python, but comes with NumPy package to create an array")
print("Arrays are multi-dimentional as well including 2D, 3D, while lists are similar to one dimentional flattened array")

The list_ data type is: <class 'list'>
The array_list data type is: <class 'numpy.ndarray'>
list is a built-in data type which is also a mutable sequence of objects while Array is not a built-in data type in Python, but comes with NumPy package to create an array
Arrays are multi-dimentional as well including 2D, 3D, while lists are similar to one dimentional flattened array


In [12]:
##Q2. Write a code to print the data type of each and every element of both the variables list_ and
##arra_list.

##Importing numpy
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]

array_list = np.array(object = list_)

##printing data type of each element in the variable list_
print("The data types of elements in list_ are:")

for i in  list_:
    print(f"The element {(i)} has datatype = {type(i)}")
    
##printing data type of each element in the variable arra_list

print("\nThe data types of elements in array_list are:")

for i in  array_list:
    print(f"The element {(i)} has datatype = {type(i)}")



The data types of elements in list_ are:
The element 1 has datatype = <class 'str'>
The element 2 has datatype = <class 'str'>
The element 3 has datatype = <class 'str'>
The element 4 has datatype = <class 'str'>
The element 5 has datatype = <class 'str'>

The data types of elements in array_list are:
The element 1 has datatype = <class 'numpy.str_'>
The element 2 has datatype = <class 'numpy.str_'>
The element 3 has datatype = <class 'numpy.str_'>
The element 4 has datatype = <class 'numpy.str_'>
The element 5 has datatype = <class 'numpy.str_'>


In [17]:
##Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
##Will there be any difference in the data type of the elements present in both the variables, list_ and
##arra_list? If so then print the data types of each and every element present in both the variables, list_
##and arra_list.

##Importing numpy
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]

array_list = np.array(object = list_, dtype = int)

##printing data type of each element in the variable list_
print("The data types of elements in list_ are:")

for i in  list_:
    print(f"The element {(i)} has datatype = {type(i)}")
    
##printing data type of each element in the variable arra_list

print("\nThe data types of elements in array_list are:")

for i in  array_list:
    print(f"The element {(i)} has datatype = {type(i)}")

print("\nThe elements in the array list have changed int64 from str")


The data types of elements in list_ are:
The element 1 has datatype = <class 'str'>
The element 2 has datatype = <class 'str'>
The element 3 has datatype = <class 'str'>
The element 4 has datatype = <class 'str'>
The element 5 has datatype = <class 'str'>

The data types of elements in array_list are:
The element 1 has datatype = <class 'numpy.int64'>
The element 2 has datatype = <class 'numpy.int64'>
The element 3 has datatype = <class 'numpy.int64'>
The element 4 has datatype = <class 'numpy.int64'>
The element 5 has datatype = <class 'numpy.int64'>

The elements in the array list have changed int64 from str


In [23]:
##Consider the below code to answer further questions:
##Q4. Write a code to find the following characteristics of variable, num_array:
##(i) shape
##(ii) size
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print(f"The dimensions of the array are {num_array.shape}")
print(f"The size of the array is {num_array.size}")
print("The array has 2 rows and 3 columns and 6 elements in it")
print(num_array)

The dimensions of the array are (2, 3)
The size of the array is 6
The array has 2 rows and 3 columns and 6 elements in it
[[1 2 3]
 [4 5 6]]


In [24]:
##Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
##creation function.

# Importing numpy module
import numpy as np

# Creating a 3*3 matrix of zeros using np.zeros function
matrix = np.zeros((3, 3))

# Printing the matrix
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
##Q6. Create an identity matrix of shape (5,5) using numpy functions?

# Importing numpy module
import numpy as np

# Creating an identity matrix of shape (5,5) using np.eye function
matrix = np.eye(5)

# Printing the matrix
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
